### ISSUE TITLE
Cannot install mattermost from the createsite dialog

### ISSUE THREAD

**Issue by cody** [uboslinux/ubos-app-mattermost#22]
Hello, @jernst--hope you're doing well! Loving UBOS so far. Thanks for all your hard work. 

**Disclaimer: I'm a self-hosting noob.**

### Problem:
Whenever I'm going through the createsite wizard, I can install and use every app I've tried ~~(including apps in the yellow beta channel)~~ _[edit: apologies--I haven't been able to run anything from the yellow channel. I incorrectly recalled that WordPress was in the the beta channel]_ except for Mattermost. After attempting an install of the mattermost app, I get the following error: 

ERROR: failed to install package(s): mattermost. Pacman says: error: target not found: mattermost

### Notes:
I'm running OBOS bare metal on an old laptop. It's an ancient Intel Core 2 Duo with ~2GB of RAM.

**Comment by jernst** [comment]
Not a bug. Mattermost currently does not exist on `green`, only on `yellow`. So if you change your release channel to `yellow` by editing `/etc/ubos/channel`, `sudo ubos-admin update` and try again, it should work.
