### ISSUE TITLE
Missing help files

### ISSUE THREAD

**Issue by julianfoad** [uboslinux/ubos-app-mattermost#4]
The Mattermost installation has links on the home page and signup page to:
/static/help/{about,privacy,terms,help}.html

but there is no '/static/help' directory.

**Comment by jernst** [comment]
I cannot find files or directories like that in the tarball we get from Mattermost. They apparently come from the config file that we use (and which is a modification of what they ship), in the "SupportSettings" category. Could you play with those some in a running installation (`/etc/mattermost/*.json`) to see whether we can get rid of them by default?

**Comment by julianfoad** [comment]
Here is the documentation for those settings:
    https://docs.mattermost.com/administration/config-settings.html#legal-and-support

**Comment by julianfoad** [comment]
Seems to me the best way to deal with this would be to change the config settings to the "default-*" values shown in that documentation. That is simple, and I think that would be much better than having dangling local links.

Another good solution, a little bit more work but not much, would be to create the referenced local pages, with each containing just a link to the corresponding "default-*" link on mattermost.com.

Either way, this could also be referred to upstream.

**Comment by jernst** [comment]
I guess this calls for some customizationpoints with default values ...
