### ISSUE TITLE
Cannot write to log file

### ISSUE THREAD

**Issue by jernst** [uboslinux/ubos-app-mattermost#6]
Needs to be provisioned during deploy, so `mattermost:mattermost` can write to it.

**Comment by jernst** [comment]
To test, create a site running `mattermost`. Once it is up and running, go to `/var/log` and check that a file exists whose name starts with `mattermost` and that is not empty. I don't know exactly what Mattermost logs, but presumably things like "application was started".

**Comment by lastdot** [comment]
The log file for "mattermost" does exist but it is empty.

**Comment by jernst** [comment]
Turns out that file has permissions `------S--T`. That has a very low chance of being correct. Darn octal.
Also, some other things turned out to be wrong:
* this needs to be a directory according to the system console inside mattermost
* we need to add a logrotate policy
* the config file currently specifies to log to the console and not to the file, and it needs to be the other way around
